#pragma once
#include <Arduino.h>

//DriveTrain
#define IS_GYRO false
#define IS_DISTANCE_SENSOR true

#define ROBOT_SPEED 0.3f
#define ETALON_DISTANCE 20.0f

#define ANGLE_ERROR 2.5f
#define SINGLE_ENCODER_STEP (20 * 24)
#define SINGLE_WHEEL_STEP_BY_ENCODER_TIC (PI * 100) / SINGLE_ENCODER_STEP

#define TURN_45_DEGREE_DISTANCE ((2 * sqrt(288) * PI) / 360) * 45

#define BASE_STEP_COUNT 8

//Intake
#define CLAMP_SERVO_CALMP_POS 0
#define CLAMP_SERVO_UNCLAMP_POS 20

#define CLAMP_OPEN_TIMER 0.5f

#define SEPARATOR_P 0.1f
#define SEPARATOR_D 0.0f

#define SEPARATOR_MAX_POWER 0.7
#define SEPARATOR_MOTOR_STEP 720 / 3

#define COLOR_SENSOR_CLAMP_SENS 10
#define COLOR_SENSOR_SEPARARTOR_SENS 10

#define SEPARATOR_SENS 50